name: Update Scholar Metrics

on:
  schedule:
    - cron: "0 6 * * *"   # daily 06:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run Scholar metrics script
      run: python update_metrics.py

    - name: Commit and push updated index.html
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html
        git diff --cached --quiet || git commit -m "Update Scholar metrics"
        git push
