name: Update Scholar Metrics

on:
  schedule:
    - cron: "0 6 * * *"  # Run daily at 06:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install requests

      # 4. Run Scholar metrics script
      - name: Run Scholar metrics script
        run: python update_metrics.py

      # 5. Mark repo as safe to fix dubious ownership issue
      - name: Mark repo as safe
        run: git config --global --add safe.directory /github/workspace

      # 6. Commit and push changes
      - name: Commit and push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
